package com.kpn.store.deviceinspector.model

import kotlinx.serialization.Serializable

@Serializable
data class DeviceRegisterRequest(
    val anonymous_user_id: String,
    val user_id: String,
    val device_id: String?,
    val customer_id: String,
    val platform: String,
    val fcm_id: String,
    val created_at: String? = null,
    val created_by_app: String, // KPARTNER, KSTORE, KOPS, KRIDER
    val created_by_user: String,
    val brand: String,
    val model: String,
    val device_type: String,
    val manufacturer: String,
    val hardware: String,
    val board: String,
    val android_id: String,
    val display_type: String,
    val screen_size: String,
    val app_bundle_name: String,
    val os_version: String,
    val security_patch: String,
    val carrier: String,
    val android_build: String,
    val user_agent: String,
    val java_version: String = System.getProperty("java.version", "") ?: "17",
    val user_language: String,
    val user_region: String,
    val wifi_enabled: Boolean,
    val wifi_ssid: String,
    val battery_level: Int,
    val is_app_tampered: Boolean,
    val is_auto_clicker_enabled: Boolean,
    val is_developer_option_enabled: Boolean,
    val is_debugging_enabled: Boolean,
    val is_hooking: Boolean,
    val is_device_masked: Boolean,
    val is_emulator: Boolean,
    val is_jail_broken: Boolean,
    val is_running_clone_app: Boolean,
    val is_running_gps_spoofer: Boolean,
    val is_running_screen_sharing: Boolean,
    val is_running_vpn_spoofers: Boolean,
    val is_secondary_user: Boolean,
    val is_suspicious_factory_reset: Boolean,
    val is_virtual_os: Boolean,
    val is_request_payload_tampered: Boolean,
    val session_at: String? = null,
    val session_by_app: String, // KPARTNER, KSTORE, KOPS, KRIDER
    val session_by_user: String
)